// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhslxedapgwgvjfaxynu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inloc2x4ZWRhcGd3Z3ZqZmF4eW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMDYxNTMsImV4cCI6MjA1NjY4MjE1M30.YFtK6Rpv6EUMNU8RgUMxMtvK1fssa9SebaGJleMzeVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);